services:
  backend:
    build:
      target: prod
    restart: unless-stopped
    volumes:
      - backend-db-prod:/app/data

  frontend:
    build:
      target: prod
    env_file:
      - ./frontend/.env
    restart: unless-stopped
volumes:
  backend-db-prod:
